### ISSUE TITLE
[BUG][Raspberry Pi] 2023-06-16T02:24:48.472633892Z s6-applyuidgid: fatal: unable to exec /app/server: No such file or directory

### ISSUE THREAD

**Issue by barrelltitor** [linuxserver/docker-hishtory-server#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the container with the default docker compose, when I start the container I get the following:

2023-06-16T02:24:48.472633892Z s6-applyuidgid: fatal: unable to exec /app/server: No such file or directory

### Expected Behavior

The app should run normally. This works if I move the file "/server" to "/app/server", since /app is currently empty for some reason

### Steps To Reproduce

      
Start the service on Debian 11, raspberry pi 

Get this:
2023-06-16T02:24:48.472633892Z s6-applyuidgid: fatal: unable to exec /app/server: No such file or directory

### Environment

```markdown
- OS: 
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

- How docker service was installed:
Default docker compose provided in the documentation
```

### CPU architecture

arm64

### Docker creation

```bash
services:
  hishtory-server:
    image: lscr.io/linuxserver/hishtory-server:latest
    container_name: hishtory-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - HISHTORY_POSTGRES_DB=postgresql://${HISHTORY_DB_USER}:${HISHTORY_DB_PASS}@hishtory-db:5432/hishtory?sslmode=disable
    ports:
      - 8080:8080
```

### Container logs

```bash
This is spammed:
2023-06-16T02:24:48.472633892Z s6-applyuidgid: fatal: unable to exec /app/server: No such file or directory
```

**Comment by aptalca** [comment]
Oh yes, we have a bug/typo in the aarch64 dockerfile: https://github.com/linuxserver/docker-hishtory-server/blob/main/Dockerfile.aarch64#L35

Thanks for the heads up
